### ISSUE TITLE
疑问和建议

### ISSUE THREAD

**Issue by Caiueo** [azpanel/azpanel#13]
1. 疑问
   想知道如何使得侧边导航栏全部展开

2. 建议
  虚拟机列表页，能否增加一个搜索栏，搜索IP
![如图](https://s2.loli.net/2022/03/24/Tx6bwfHCPDBmAzl.png)

**Comment by azpanel** [comment]
1.点一下左上角三条杠

2.已更新

**Comment by Caiueo** [comment]
感谢回答

关于第一点，想要的是侧边栏每一个小栏（每一项）都展开的那种，不是直接左上角三条杠（起不到每个小项都能展开的作用）...
请问该如何做才能每一小项都能展开（就是侧边导航栏，每一栏都需要下拉展开）

**Comment by azpanel** [comment]
默认打开的面板项

在 <div class="mdui-panel-item"></div> 元素上添加类 .mdui-panel-item-open 即可使该面板项处于默认打开状态。
