### ISSUE TITLE
BT安装出现错误

### ISSUE THREAD

**Issue by Pinkyou1** [azpanel/azpanel#15]
可以更新一下Centos的 宝塔教程吗 
请问这是哪里出错
#0 [8]ErrorException in [Config.php line 20]()
Trying to get property 'type' of non-object
class Config extends Model
{
    protected $pk = 'id';
    protected $table = 'config';

    public static function obtain($key)
    {
        $item = self::where('item', $key)->find();
        
        if ($item->type == 'bool') {
            return (bool) $item->value;
        } elseif ($item->type == 'int') {
            return (int) $item->value;
        } else {
            return (string) $item->value;
        }
    }

    public static function class($name)

**Comment by azpanel** [comment]
导入 database/config.sql

**Comment by Pinkyou1** [comment]
您好，我看到教程安装完GIt后 发现cp不到数据库，是不是应该先git源码然后再导入数据库
顺序是这样的
yum -y install git
yum -y install git

git clone https://github.com/azpanel/azpanel.git .

cp database/azure.sql /www/backup/database
cp database/config.sql /www/backup/database

chmod 755 -R *
chown www -R *
composer install

**Comment by azpanel** [comment]
谢谢指正，已修改

**Comment by Pinkyou1** [comment]
客气，我导入config.sql后 还出现了这个问题 
#0 [8]ErrorException in [Config.php line 20]()
Trying to get property 'type' of non-object
