### ISSUE TITLE
SQLSTATE[HY000] [1105] unknown error: Code: UNAVAILABLE server does not allow insecure connections, client must use SSL/TLS

### ISSUE THREAD

**Issue by aiastia** [azpanel/azpanel#16]
远程数据库需要ssl 才能链接

**Comment by azpanel** [comment]
https://www.thinkphp.cn/topic/70111.html

**Comment by aiastia** [comment]
搞定了 这样 就可以 了 'params'          => [PDO::MYSQL_ATTR_SSL_CA=>'/etc/ssl/certs/ca-certificates.crt'],

**Comment by aiastia** [comment]
配置后网站正常访问 
但是执行 

php think migrate:run
会提示这个。

                                                                                                           
  [InvalidArgumentException]                                                                               
  There was a problem connecting to the database: SQLSTATE[HY000] [1105] unknown error: Code: UNAVAILABLE  
  server does not allow insecure connections, client must use SSL/TLS

**Comment by aiastia** [comment]
已配置 params 选项 
方案一
PDO::MYSQL_ATTR_SSL_CA=>'/var/lib/mysql/ca.pem',
PDO::MYSQL_ATTR_SSL_CERT=>'/var/lib/mysql/client-cert.pem',
PDO::MYSQL_ATTR_SSL_KEY=>'/var/lib/mysql/client-key.pem',
PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false
方案二 

 'params' => [PDO::MYSQL_ATTR_SSL_CA=>'/etc/ssl/certs/ca-certificates.crt'],

都不行

**Comment by azpanel** [comment]
无法提供更多帮助，请前往 https://github.com/top-think/think-migration/issues

**Comment by aiastia** [comment]
> 无法提供更多帮助，请前往 https://github.com/top-think/think-migration/issues

用的planetscale.com 的数据库 。config 里面配置了ssl 网站访问正常 但是 php think migrate:run提示 ssl 必须。。。

**Comment by azpanel** [comment]
```
/home/wwwroot/azpanel/vendor/topthink/think-migration/src/Command.php:57
```
你可以在这个文件的下面加上
```
'params' => $config['params'],
```
试试看

**Comment by aiastia** [comment]
![12539A91-E862-4C40-8157-CF0351DE6C07](https://user-images.githubusercontent.com/19776350/161389868-b5cca012-edac-4c2c-8c6f-5838f2907752.jpeg)
![684214D3-4598-47F4-ACB2-854E659671B8](https://user-images.githubusercontent.com/19776350/161389869-f41b2903-b591-4512-879d-d83a1be6230a.jpeg)

php think migrate:run仍然出现错误 网站访问登陆正常。。。

**Comment by aiastia** [comment]
需要提供什么日志吗
![F180FC6D-1D18-4CC4-ACBD-72997EA058F6](https://user-images.githubusercontent.com/19776350/161390165-9d28f71d-c272-432a-b307-c93e99319d84.jpeg)

**Comment by aiastia** [comment]
![B56EB09F-F84F-43D4-AF1F-97CF1D22FCF1](https://user-images.githubusercontent.com/19776350/161390242-2115fcec-31fc-4767-864e-ff566ee9db35.jpeg)

**Comment by azpanel** [comment]
别折腾了，用本地数据库吧
