### ISSUE TITLE
支持自动识别面板导出的账号信息

### ISSUE THREAD

**Issue by Jonathon52306** [azpanel/azpanel#19]
支持自动识别面板导出的账号信息 自动填充所有需要的账户信息
格式为
`{"login_user":"example@example.com","login_passwd":"password","subscription_id":"11111111-1111-1111-1111-111111111111","appId":"11111111-1111-1111-1111-111111111111","password":"AAAAAAAAAAAAAAAAAAA","tenant":"11111111-1111-1111-1111-111111111111"}`

**Comment by azpanel** [comment]
现在可以了。

**Comment by SkyAerope** [comment]
目前此功能使用出现问题。
同为最新版本的面板，A面板提取账户json输入到B面板，出现错误（见下图）：
![image](https://user-images.githubusercontent.com/81958172/180709076-311d7b22-9273-4855-8717-e16df5b57a29.png)
