### ISSUE TITLE
加个功能

### ISSUE THREAD

**Issue by 12123ads** [azpanel/azpanel#20]
能不能支持在面板端查看订阅赠金剩余

**Comment by azpanel** [comment]
你如果想要这个功能，可以参考rest api文档，看看怎么样在浏览器通过“try it”获取到

https://docs.microsoft.com/zh-cn/rest/api/consumption/balances

**Comment by bingbaga** [comment]
说实话，这个我也研究过，一直没找到billingaccountid！！！！

**Comment by azpanel** [comment]
> 说实话，这个我也研究过，一直没找到billingaccountid！！！！

我也是，哈哈哈哈哈，开个工单问问客服吧

**Comment by bingbaga** [comment]
> > 说实话，这个我也研究过，一直没找到billingaccountid！！！！
> 
> 我也是，哈哈哈哈哈，开个工单问问客服吧

我猜的是，可能我们不是商业用户，没实际扣款，可能就在成本页找不到这，网上搜的地方没看到这字段

**Comment by azpanel** [comment]
研究过相关api，没弄成，用新更新的“预估费用”功能凑合吧
