### ISSUE TITLE
可以增加对f系列ipv6自动配置吗？

### ISSUE THREAD

**Issue by Oldming1** [azpanel/azpanel#25]
可以增加对f系列ipv6自动配置吗？希望增加ipv6配置手动配置实属重复。ipv6配置具体https://blog.csdn.net/weixin_33433927/article/details/119476696   
也就是给子网和地址空间添加ipv6然后新增一个ipv6ip即可，希望大佬能够增加一下关于对ipv6支持谢谢

**Comment by JusufUs** [comment]
附议+1

**Comment by visense** [comment]
如果加上这个功能就666了

**Comment by moranno** [comment]
我也刚好需要这个功能，希望能开发下，可以提供资金支持。USDT

**Comment by moranno** [comment]
这里看到相关文档：https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/load-balancer/ipv6-add-to-existing-vnet-powershell.md

**Comment by azpanel** [comment]
现在可以了。
