### ISSUE TITLE
大佬这是什么情况？

### ISSUE THREAD

**Issue by Titans11** [azpanel/azpanel#30]
输入这个之后：

apt-get -y install git
git clone https://github.com/azpanel/azpanel.git .
cp database/azure.sql /www/backup/database
cp database/config.sql /www/backup/database
chmod 755 -R *
chown www -R *
composer install

导致下面这个：
root@ip-1XXXXXXX:/www/wwwroot/bt.XXXXXXXX# git clone https://github.com/azpanel/azpanel.git .

fatal: destination path '.' already exists and is not an empty directory.

之后各种No such file or directory？

换了几个实例系统了，依然出现这个问题。虚拟机是AWS EC2，系统是 debian10，使用的是你的宝塔教程安装搭建，这一步一直出现这种错误，到底是什么情况？

**Comment by azpanel** [comment]
cd /www/wwwroot
git clone https://github.com/azpanel/azpanel.git azpanel

然后bt面板将网站目录设置成azpanel

**Comment by Titans11** [comment]
非常感谢，完美解决， 作者很强大，还开源免费，应该大力推广出去，赞！我附上 我较为详细 的 解决办法，留给有缘人看，当然，如果作者能修复bug，就更好了。

第一步：cd /www/wwwroot(回车)


第二步：

apt-get -y install git
git clone https://github.com/azpanel/azpanel.git azpanel（回车）


第三步：cd /www/wwwroot/azpanel（回车）


第四步：

cp database/azure.sql /www/backup/database
cp database/config.sql /www/backup/database
chmod 755 -R *
chown www -R *
composer install（回车）

自此完美安装成功，感谢作者的慷慨！
