### ISSUE TITLE
同时创建多个虚拟机会出一点问题

### ISSUE THREAD

**Issue by bashensanbuqu** [azpanel/azpanel#34]
![image](https://user-images.githubusercontent.com/64031631/175032076-6a2527c6-d706-4a79-bef9-a7001fe994ff.png)
![image](https://user-images.githubusercontent.com/64031631/175032368-65e334eb-8806-4462-b959-216908807b8a.png)
同时创建几十个虚拟机的时候.  总会出现几个报错  [创建失败]   但机器都会创建好,  可是得手动点更新资源, 才能看到.  还有就是失败的机器  备注是空的了

**Comment by myitcloud** [comment]
咋同时创建多个哇，我用博主的 直接提示参数不对

**Comment by azpanel** [comment]
任务的进程状态显示现在可以互不干扰了（涉及到创建虚拟机，刷新账户订阅状态，更换ip，更换虚拟机硬盘）

【如何更新】

在网站根目录下执行
```
git checkout .
git pull
composer update
php think migrate:run
```
