### ISSUE TITLE
不同地区虚拟机配置的金额可以同步一下吗

### ISSUE THREAD

**Issue by PeiHao666** [azpanel/azpanel#38]
不同地区，同一配置的虚拟机在官网价格不一样，但是在面板上每个地区显示的价格都一样，麻烦可以同步一下官方的配置金额吗？谢谢

**Comment by azpanel** [comment]
搜集整理数据费时费力，不考虑

**Comment by SkyAerope** [comment]
试试这个？https://azureprice.net/
