### ISSUE TITLE
邮箱只支持465端口吗

### ISSUE THREAD

**Issue by xkatld** [azpanel/azpanel#4]
设置了几个587都是连不上

**Comment by azpanel** [comment]
到底哪个端口，测试发信有无报错

**Comment by xkatld** [comment]
![image](https://user-images.githubusercontent.com/36999228/158056859-76defa71-2009-4a92-abe8-3aeade525830.png)
你好 发件死活连不上 试过qq gmail 自建邮箱都不行

**Comment by xkatld** [comment]
确认发件信息账号无误

**Comment by azpanel** [comment]
所以你smtp host填的什么？服务器上ping通么？服务器端口全开了吗？

**Comment by xkatld** [comment]
都开了 用465 gmail可以发 587发不了
