### ISSUE TITLE
创建机子页面拒绝访问

### ISSUE THREAD

**Issue by 12123ads** [azpanel/azpanel#42]
我尝试过重建网站，还是会这样
![图片](https://user-images.githubusercontent.com/69107029/183689168-2d22553d-d9e9-4d49-b7fb-34e101a8ced8.png)

**Comment by azpanel** [comment]
访问的路径倒是贴出来啊

**Comment by 12123ads** [comment]
域名/user/server/azure/create

**Comment by azpanel** [comment]
php版本：
thinkphp版本：
是否执行过“php think migrate:run”：

**Comment by 12123ads** [comment]
php版本：8.0.18
thinkphp版本：6.0.13LTS
执行过“php think migrate:run”

**Comment by azpanel** [comment]
感觉是路由匹配问题，换php7.4

**Comment by 12123ads** [comment]
好，我试试

**Comment by 12123ads** [comment]
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.30. in /www/wwwroot/*/vendor/composer/platform_check.php on line 24


换了提示这个

**Comment by 12123ads** [comment]
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.30. in /www/wwwroot/az.xzh.gs/vendor/composer/platform_check.php on line 24


换了7.4提示这个

**Comment by 12123ads** [comment]
可以了，谢谢

**Comment by hulisang** [comment]
@azpanel 大佬我也有这个问题，但是换php7.4之后报错
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.21. in /www/wwwroot/azpanel.178145.xyz/vendor/composer/platform_check.php on line 24
说我php版本小于8.0.2

**Comment by azpanel** [comment]
> @azpanel 大佬我也有这个问题，但是换php7.4之后报错 Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.21. in /www/wwwroot/azpanel.178145.xyz/vendor/composer/platform_check.php on line 24 说我php版本小于8.0.2

composer install --prefer-source
