### ISSUE TITLE
能否增加虚拟机选择代次

### ISSUE THREAD

**Issue by jeson998** [azpanel/azpanel#43]
能否增加虚拟机选择代次？
目前是默认第二代，我是有需要第一代
还有一键增加辅助IP

**Comment by azpanel** [comment]
修改AzureList.php，gen2改gen1
辅助ip不加，请买别的面板

**Comment by jeson998** [comment]
可以付费添加这个辅助IP的功能吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月10日(星期三) 晚上7:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [azpanel/azpanel] 能否增加虚拟机选择代次 (Issue #43)





 
修改AzureList.php，gen2改gen1
 辅助ip不加，请买别的面板
 
&mdash;

**Comment by jeson998** [comment]
大佬，我按照你教我的，改了gen1，不能创建，提示映像有问题，我试着去API文档获取了下SKU，好像是没有叫gen1的Debian镜像，是不是需要改虚拟机的创建那地方呢？
请指点下，在此拜谢！
最下面我附上获取到的SKU列表JSON原文











[
&nbsp; {
&nbsp; &nbsp; "properties": {
&nbsp; &nbsp; &nbsp; "automaticOSUpgradeProperties": {
&nbsp; &nbsp; &nbsp; &nbsp; "automaticOSUpgradeSupported": false
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },
&nbsp; &nbsp; "location": "eastasia",
&nbsp; &nbsp; "name": "11",
&nbsp; &nbsp; "id": "/Subscriptions/68fe8c75-b356-4e1f-bbf4-a8c9bda622ad/Providers/Microsoft.Compute/Locations/eastasia/Publishers/Debian/ArtifactTypes/VMImage/Offers/debian-11/Skus/11"
&nbsp; },
&nbsp; {
&nbsp; &nbsp; "properties": {
&nbsp; &nbsp; &nbsp; "automaticOSUpgradeProperties": {
&nbsp; &nbsp; &nbsp; &nbsp; "automaticOSUpgradeSupported": false
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },
&nbsp; &nbsp; "location": "eastasia",
&nbsp; &nbsp; "name": "11-backports",
&nbsp; &nbsp; "id": "/Subscriptions/68fe8c75-b356-4e1f-bbf4-a8c9bda622ad/Providers/Microsoft.Compute/Locations/eastasia/Publishers/Debian/ArtifactTypes/VMImage/Offers/debian-11/Skus/11-backports"
&nbsp; },
&nbsp; {
&nbsp; &nbsp; "properties": {
&nbsp; &nbsp; &nbsp; "automaticOSUpgradeProperties": {
&nbsp; &nbsp; &nbsp; &nbsp; "automaticOSUpgradeSupported": false
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },
&nbsp; &nbsp; "location": "eastasia",
&nbsp; &nbsp; "name": "11-backports-arm64",
&nbsp; &nbsp; "id": "/Subscriptions/68fe8c75-b356-4e1f-bbf4-a8c9bda622ad/Providers/Microsoft.Compute/Locations/eastasia/Publishers/Debian/ArtifactTypes/VMImage/Offers/debian-11/Skus/11-backports-arm64"
&nbsp; },
&nbsp; {
&nbsp; &nbsp; "properties": {
&nbsp; &nbsp; &nbsp; "automaticOSUpgradeProperties": {
&nbsp; &nbsp; &nbsp; &nbsp; "automaticOSUpgradeSupported": false
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },
&nbsp; &nbsp; "location": "eastasia",
&nbsp; &nbsp; "name": "11-backports-gen2",
&nbsp; &nbsp; "id": "/Subscriptions/68fe8c75-b356-4e1f-bbf4-a8c9bda622ad/Providers/Microsoft.Compute/Locations/eastasia/Publishers/Debian/ArtifactTypes/VMImage/Offers/debian-11/Skus/11-backports-gen2"
&nbsp; },
&nbsp; {
&nbsp; &nbsp; "properties": {
&nbsp; &nbsp; &nbsp; "automaticOSUpgradeProperties": {
&nbsp; &nbsp; &nbsp; &nbsp; "automaticOSUpgradeSupported": false
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },
&nbsp; &nbsp; "location": "eastasia",
&nbsp; &nbsp; "name": "11-gen2",
&nbsp; &nbsp; "id": "/Subscriptions/68fe8c75-b356-4e1f-bbf4-a8c9bda622ad/Providers/Microsoft.Compute/Locations/eastasia/Publishers/Debian/ArtifactTypes/VMImage/Offers/debian-11/Skus/11-gen2"
&nbsp; }
]

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azpanel/azpanel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月10日(星期三) 晚上7:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azpanel/azpanel] 能否增加虚拟机选择代次 (Issue #43)





 
修改AzureList.php，gen2改gen1
 辅助ip不加，请买别的面板

**Comment by azpanel** [comment]
更新到最新，默认的镜像列表里，没有 gen2 标识的就是 gen1 代的镜像
