### ISSUE TITLE
SMTPSecure自定义

### ISSUE THREAD

**Issue by Apocalypsor** [azpanel/azpanel#5]
关于在
```
app/controller/Notify.php
```
中的
```
$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
```
可以提供可选项自定义为`PHPMailer::ENCRYPTION_STARTTLS`吗，微软用于发信只能 STARTTLS

**Comment by azpanel** [comment]
https://github.com/azpanel/azpanel/commit/e9f017858019cc53aeafe814c0bd6c049bce7702
