### ISSUE TITLE
此虚拟机 ipv4 是静态类型地址，不支持更换

### ISSUE THREAD

**Issue by llyang1** [azpanel/azpanel#52]
1\部分实例无法更换,部分实例可以更换
2\所有实例都是动态IPv4
3\都没有分配过IPv6
4\以前都可以随意更换IP
5\手工进入微软面板,停止-启动,可以更换IPv4
6\在虚拟机详情-外部网络,可以看到类型：Dynamic

估计UserAzureServer.php中对于IPv6的判断,微软最近出现了变化

**Comment by azpanel** [comment]
可以注释掉UserAzureServer.php的710-712行
