### ISSUE TITLE
添加账号post返回500，显示页面错误

### ISSUE THREAD

**Issue by RandallAnjie** [azpanel/azpanel#53]
使用宝塔安装，搭建完成后测试发现添加账号一直卡在进行中，查看控制台发现500报错

![image](https://user-images.githubusercontent.com/84122428/206830177-53bfbd2f-ef04-459e-b966-b9f944f9df3f.png)

![image](https://user-images.githubusercontent.com/84122428/206830125-ae56871e-cab0-4701-8068-0c0b2b41783c.png)

![image](https://user-images.githubusercontent.com/84122428/206830100-e59a47d4-957d-418f-8247-516f5cc6a7fd.png)

**Comment by azpanel** [comment]
.env 开启 debug 模式后再看控制台的报错哈

**Comment by RandallAnjie** [comment]
是文件夹权限问题，文件夹权限递归755就好了
