### ISSUE TITLE
个人资料页面报错，新建虚拟机页面拒绝访问

### ISSUE THREAD

**Issue by Andy-Chuck** [azpanel/azpanel#54]
一步一步按照宝塔面板教程搭建的，安装完成后个人资料页面报错，新建虚拟机页面拒绝访问。手动在数据库里补全个人信息后资料页面正常，但仍无法创建虚拟机。

宝塔面板，Nginx 1.22，PHP 8.1，Mysql 5.7

![1](https://user-images.githubusercontent.com/54295429/212260484-89a45f02-70a7-4c60-9590-2dacff0d138b.png)
个人资料

![2](https://user-images.githubusercontent.com/54295429/212260492-75689c60-2cae-4cdc-b7a2-d8eb2992a39d.png)
新建小鸡

![3](https://user-images.githubusercontent.com/54295429/212260496-0e8d5cf4-f8c0-4fa5-bb59-8b1be746c38b.png)
管理后台用户个人资料

**Comment by azpanel** [comment]
没有对php8适配，换php7。。。

**Comment by azpanel** [comment]
已经适配了。
