### ISSUE TITLE
宝塔安装，最后执行php think migrate:run 报错。

### ISSUE THREAD

**Issue by wythe-zz** [azpanel/azpanel#56]
宝塔安装，最后执行php think migrate:run 报错。
试了几次都是最后一步出错，网站提示页面报错。
![WX20230915-000201](https://github.com/azpanel/azpanel/assets/3424197/13e446b6-7ff3-4363-a83e-607c23395caa)
![WX20230915-000337](https://github.com/azpanel/azpanel/assets/3424197/74aad398-7c7b-4035-bb1a-293db12976d4)

**Comment by agczsz** [comment]
出现同样情况

**Comment by mmtigewo00** [comment]
出现同样情况

**Comment by azpanel** [comment]
已经修复。新版本的 `think-migrate` 不让在 `migrate` 文件里调用 `insert` 方法了，所以才会有这个错误。重新拉取，然后执行
```
php think migrate:run
php think seed:run
```
**注意都只需要执行一次**
