### ISSUE TITLE
反馈一个ipv6的问题。

### ISSUE THREAD

**Issue by alowuden** [azpanel/azpanel#57]
博主你好，首先感谢你开发维护这个为爱发电的项目，我使用中遇到了一个问题，我添加的是新加坡区域的机器类型为t2.micro，命名为A，勾选了ipv6选项，创建成功后，国内机B 和国外机C 去ping A的v6地址，都是ping不通的状态。A去pingB和C的ipv6地址都是能通的（B和C之前都是正常的）。包括iperf3去对拉，也是这个状态。
猜测是不是ipv6的防火墙或者出入站规则有问题？大佬有时间的话可以看看究竟是什么问题吗？再次感谢大佬的付出~

**Comment by 2605759123** [comment]
我也一样的问题

**Comment by azpanel** [comment]
好了。
