### ISSUE TITLE
添加账号报错

### ISSUE THREAD

**Issue by iddddg** [azpanel/azpanel#6]
原因是因为调用getAzureSubscription方法时，https://management.azure.com/subscriptions?api-version=2020-01-01 接口返回的json如下
```json
{
    "value": [],
    "count": {
        "type": "Total",
        "value": 0
    }
}
```
换了两个az 100学生号都是这样，token也能获取，请问是哪里操作不对吗？

**Comment by azpanel** [comment]
使用文档中心给出的命令获取api参数

**Comment by iddddg** [comment]
> 使用文档中心给出的命令获取api参数

谢谢解答，请问能给个文档的链接嘛，谢谢

**Comment by azpanel** [comment]
？
你的域名/user/docs

**Comment by iddddg** [comment]
> ？ 你的域名/user/docs

对不起，没有好好看网页，谢谢大佬解答
