### ISSUE TITLE
最新版点击虚拟机详情会报错

### ISSUE THREAD

**Issue by LinnBenson** [azpanel/azpanel#7]
#0 [8]ErrorException in [fc487a4930247e849581db3c91f1f92c.php line 489]()
![image](https://user-images.githubusercontent.com/82112667/159044828-f3b6eb87-f890-48ca-b940-2e4f4edbb60b.png)

**Comment by azpanel** [comment]
php think migrate:status

**Comment by LinnBenson** [comment]
![image](https://user-images.githubusercontent.com/82112667/159045751-b7ceeb31-02fb-4507-9e6b-b2564809f41b.png)
这样执行吗？还是一样报错。PHP也试着重启了

**Comment by azpanel** [comment]
全部的虚拟机点击虚拟机详情都会这样么？
phpmyadmin进入数据库，查看azure_server的表结构，dsik_details字段的默认值是null么，所涉及的虚拟机，此字段的值是？

**Comment by LinnBenson** [comment]
所有虚拟机点击虚拟机详情都这样。
![image](https://user-images.githubusercontent.com/82112667/159047004-d9b49ba3-8d54-4b93-84ef-7a9bcf109a65.png)
azure_server的表结构，dsik_details字段的默认值是null。
其中一个虚拟机的dsik_details是：
`{"name":"myVMosdisk","id":"\/subscriptions\/db6d0346-9161-4956-94cc-d14f4928571c\/resourceGroups\/GROUPJ1CO6O\/providers\/Microsoft.Compute\/disks\/myVMosdisk","type":"Microsoft.Compute\/disks","location":"eastasia","managedBy":"\/subscriptions\/db6d0346-9161-4956-94cc-d14f4928571c\/resourceGroups\/groupj1Co6o\/providers\/Microsoft.Compute\/virtualMachines\/Core","sku":{"name":"Standard_LRS","tier":"Standard"},"properties":{"osType":"Linux","hyperVGeneration":"V1","supportedCapabilities":{"acceleratedNetwork":true},"creationData":{"createOption":"FromImage","imageReference":{"id":"\/Subscriptions\/76f3e1e5-21ef-4ad3-95bb-0d612d062959\/Providers\/Microsoft.Compute\/Locations\/eastasia\/Publishers\/debian\/ArtifactTypes\/VMImage\/Offers\/debian-10\/Skus\/10\/Versions\/0.20220310.944"}},"diskSizeGB":64,"diskIOPSReadWrite":500,"diskMBpsReadWrite":60,"encryption":{"type":"EncryptionAtRestWithPlatformKey"},"networkAccessPolicy":"AllowAll","timeCreated":"2022-03-14T18:49:09.6768763+00:00","provisioningState":"Succeeded","diskState":"Attached","diskSizeBytes":68719476736,"uniqueId":"2e78350e-1d3a-4ca0-a61b-aa5f0fc5a9ad"}}`

**Comment by azpanel** [comment]
打了个补丁，更新一下应该就没问题了

**Comment by LinnBenson** [comment]
是的，已经好了，谢谢大佬帮助
